drop table if exists item CASCADE;
create TABLE item(
    id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
    );

-- 해당 경로에 해당 파일 이름으로 만들면 메모리가 뜨면서 DB를 초기화 해준다 (Embeded ? ) 테스트할때 이용하자